In [39]:
import os
import sys
import numpy as np
import cPickle
import random
import math
import h5py
from collections import defaultdict as dd
import tensorflow as tf

from keras import layers
from keras.models import Sequential
from keras.layers import Input, Dense, Activation, BatchNormalization, Flatten
from keras.layers.embeddings import Embedding
from keras.models import Model
from keras.utils import layer_utils
from keras.utils.data_utils import get_file
from keras.applications.imagenet_utils import preprocess_input
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences



np.random.seed(1)

In [2]:
# Initialize parameters
DATASET = 'citeseer'

embedding_size = 50
learning_rate = 0.1
batch_size = 200
neg_samp = 1
model_file = 'trans.model'

window_size = 3
path_size = 10

g_batch_size = 200
g_learning_rate = 0.01
g_sample_size = 100

use_feature = True
update_emb = True
layer_loss =  True

In [105]:
# Load the dataset
NAMES = ['x', 'y', 'tx', 'ty', 'graph']
OBJECTS = []
for i in range(len(NAMES)):
    OBJECTS.append(cPickle.load(open("/hdd2/graph_embedding/planetoid/data/trans.{}.{}".format(DATASET, NAMES[i]))))
x, y, tx, ty, graph = tuple(OBJECTS)

In [ ]:
# Sample a collections of paths from the graph

In [23]:
def initialize_parameters(l_emd_f_W_size, l_x_hid_W_size, l_y_W_size):
    """
    Initializes weight parameters to build a neural network with tensorflow. The shapes are:
                        W1 : [4, 4, 3, 8]??
                        W2 : [2, 2, 8, 16]?
    Returns:
    parameters -- a dictionary of tensors containing W1, W2
    """
    
    tf.set_random_seed(1)
    
    l_emd_f_W = tf.Variable(tf.truncated_normal(l_emd_f_W_size,
                            stddev=1.0 / math.sqrt(l_emd_f_W_size[1])))
    l_emd_f_b = tf.Variable(tf.zeros([l_emd_f_W_size[0]]))
    
    l_x_hid_W = tf.get_variable('l_x_hid_W', shape = l_x_hid_W_size,
                               initializer = tf.contrib.layers.xavier_initializer(uniform=True, seed = 1))
    l_x_hid_b = tf.get_variable('l_x_hid_b', shape = [l_x_hid_W_size[0], 1],
                               initializer = tf.contrib.layers.xavier_initializer(uniform=True, seed = 1))
    l_y_W = tf.get_variable('l_y_W', shape = l_y_W_size,
                           initializer = tf.contrib.layers.xavier_initializer(uniform=True, seed = 1))
    l_y_b = tf.get_variable('l_y_b', shape = [l_y_W_size[0], 1],
                           initializer = tf.contrib.layers.xavier_initializer(uniform=True, seed = 1))
    
    parameters = {'l_emd_f_W': l_emd_f_W,
                  'l_emd_f_b': l_emd_f_b,
                  'l_x_hid_W': l_x_hid_W,
                  'l_x_hid_b': l_x_hid_b,
                  'l_y_W': l_y_W,
                  'l_y_b': l_y_b}
    
    return parameters

In [24]:
tf.reset_default_graph()
with tf.Session() as sess_test:
    parameters = initialize_parameters([3,3], [3,4], [4,2])
    init = tf.global_variables_initializer()
    sess_test.run(init)
    print(str(parameters['l_emd_f_W'].eval()))


[[-0.38732192  0.12907903  0.46030581]
 [ 0.05552411  0.5345757   1.12406611]
 [ 0.40012899  0.12259372 -0.88986874]]


In [ ]:
def compute_supervised_cost(a_C, a_G):
    """
    Computes the supervised cost
    
    Arguments:  todo
    a_C -- tensor of dimension (1, n_H, n_W, n_C), hidden layer activations representing content of the image C 
    a_G -- tensor of dimension (1, n_H, n_W, n_C), hidden layer activations representing content of the image G
    
    Returns: 
    J_supervised -- scalar that you compute using equation 1 above.
    """
    
    return J_supervised

In [1]:
def compute_embedding_weight():
    """
    Computes the embedding weights
    
    Return:
    reweight -- vector for each path
    """
    
    return reweight
    

In [ ]:
def compute_embedding_cost():
    """
    Computes the embedding cost
    
    Returns:
    J_embedding -- scalar that you compute using equation x above.
    """
    
    return J_embedding

In [110]:
def create_placeholders():
    """
    Creates the placeholders for the tensorflow session.
    
    Arguments:
    n_x -- scalar, height of an input image
    n_W0 -- scalar, width of an input image
    n_C0 -- scalar, number of channels of the input
    n_y -- scalar, number of classes
        
    Returns:
    X -- placeholder for the data input, of shape [n_x, None] and dtype "float"
    Y -- placeholder for the input labels, of shape [None, n_y] and dtype "float"
    """

    
    x_sym = tf.placeholder(tf.float32, shape = [None, num_ver], name = 'x')
    y_sym = tf.placeholder(tf.int32, shape = [None, 2], name = 'y')
    g_sym = tf.placeholder(tf.int32, shape = [200], name = 'g')
    gy_sym = tf.placeholder(tf.int32, shape = [200, 1], name = 'gy')
    ind_sym = tf.placeholder(tf.int32, shape = [num_ver], name = 'ind')
    
    
    return x_sym, y_sym, g_sym, gy_sym, ind_sym

In [111]:
x_sym, y_sym, g_sym, gy_sym, ind_sym = create_placeholders()
embeddings = tf.Variable(
    tf.random_uniform([vocabulary_size, embedding_size], -1.0, 1.0))
softmax_weights = tf.Variable(
    tf.truncated_normal([vocabulary_size, embedding_size],
                        stddev=1.0 / math.sqrt(embedding_size)))
softmax_biases = tf.Variable(tf.zeros([vocabulary_size]))
l_emd_f = tf.nn.embedding_lookup(embeddings, g_sym)

In [112]:
print(l_x_hid.shape)
print(l_emd_f.shape)
print(ind_sym)
print(embeddings)
print(softmax_weights)

(?, 6)
(200, 50)
Tensor("ind_17:0", shape=(3327,), dtype=int32)
<tf.Variable 'Variable_66:0' shape=(3327, 50) dtype=float32_ref>
<tf.Variable 'Variable_67:0' shape=(3327, 50) dtype=float32_ref>


In [76]:
embeddings.shape

TensorShape([Dimension(3327), Dimension(50)])

In [113]:
# def build():
"""
Builds the model.
"""
num_sampled = 64
num_ver = max(graph.keys()) + 1
vocabulary_size = num_ver

# graph = tf.Graph()

# with graph.as_default(), tf.device('/cpu:0'):
    
x_sym, y_sym, g_sym, gy_sym, ind_sym = create_placeholders()



# word embedding
embeddings = tf.Variable(
    tf.random_uniform([vocabulary_size, embedding_size], -1.0, 1.0))
softmax_weights = tf.Variable(
    tf.truncated_normal([vocabulary_size, embedding_size],
                        stddev=1.0 / math.sqrt(embedding_size)))
softmax_biases = tf.Variable(tf.zeros([vocabulary_size]))
l_emd_f = tf.nn.embedding_lookup(embeddings, g_sym)

# model = Sequential()
# model.add(Embedding(vocabulary_size, embedding_size, input_length = path_size))

##

l_x_hid = tf.layers.dense(inputs = x_sym, units = y.shape[1], activation = tf.nn.softmax)
if use_feature:
#     l_emd_f = tf.layers.dense(inputs = l_emd_f, units = y.shape[1], activation = tf.nn.softmax)
    l_y = tf.concat([l_x_hid, l_emd_f], axis = 1)
    l_y = tf.layers.dense(inputs = l_y, units = y.shape[1], activation = tf.nn.softmax)
else:
    l_y = tf.layers.dense(inputs = l_emd_f, units = y.shape[1], activation = tf.nn.softmax)

loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = l_y, labels = y_sym))

if layer_loss and use_feature:
    loss += tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = l_x_hid, labels = y_sym))
    loss += tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits = l_emd_f, labels = y_sym))

if neg_samp == 0:
    pass
else:
    g_loss = tf.reduce_mean(
        tf.nn.sampled_softmax_loss(weights=softmax_weights, biases=softmax_biases, 
                                   inputs = l_emd_f, labels = gy_sym, 
                                   num_sampled = num_sampled, 
                                   num_classes = vocabulary_size))

optimizer = tf.train.AdamOptimizer(2.0).minimize(loss)

g_optimizer = tf.train.AdamOptimizer(2.0).minimize(g_loss)

In [4]:
def gen_train_inst():
    """generator for batches for classification loss.
    """
    while True:
        ind = np.array(np.random.permutation(x.shape[0]), dtype = np.int32)
        i = 0
        while i < ind.shape[0]:
            j = min(ind.shape[0], i + batch_size)
            yield x[ind[i: j]], y[ind[i: j]], ind[i: j]
            i = j

In [5]:
def gen_label_graph():
    """generator for batches for label context loss.
    """
    labels, label2inst, not_label = [], dd(list), dd(list)
    for i in range(x.shape[0]):
        flag = False
        for j in range(y.shape[1]):
            if y[i, j] == 1 and not flag:
                labels.append(j)
                label2inst[j].append(i)
                flag = True
            elif y[i, j] == 0:
                not_label[j].append(i)

    while True:
        g, gy = [], []
        for _ in range(g_sample_size):
            x1 = random.randint(0, x.shape[0] - 1)
            label = labels[x1]
            if len(label2inst) == 1: continue
            x2 = random.choice(label2inst[label])
            g.append([x1, x2])
            gy.append(1.0)
            for _ in range(neg_samp):
                g.append([x1, random.choice(not_label[label])])
                gy.append( - 1.0)
        yield np.array(g, dtype = np.int32), np.array(gy, dtype = np.float32)

In [6]:
def gen_graph():
    """generator for batches for graph context loss.
    """

    num_ver = max(graph.keys()) + 1

    while True:
        ind = np.random.permutation(num_ver)
        i = 0
        while i < ind.shape[0]:
            g, gy = [], []
            j = min(ind.shape[0], i + g_batch_size)
            for k in ind[i: j]:
                if len(graph[k]) == 0: continue
                path = [k]
                for _ in range(path_size):
                    path.append(random.choice(graph[path[-1]]))
                for l in range(len(path)):
                    for m in range(l - window_size, l + window_size + 1):
                        if m < 0 or m >= len(path): continue
                        g.append([path[l], path[m]])
                        gy.append(1.0)
                        for _ in range(neg_samp):
                            # if the random number euqals to path[m], the it creates noise!
                            g.append([path[l], random.randint(0, num_ver - 1)])
                            gy.append(- 1.0)
            yield np.array(g, dtype = np.int32), np.array(gy, dtype = np.float32)
            i = j

In [7]:
def init_train(self, init_iter_label, init_iter_graph):
    """pre-training of graph embeddings.
    init_iter_label (int): # iterations for optimizing label context loss.
    init_iter_graph (int): # iterations for optimizing graph context loss.
    """
    for i in range(init_iter_label):
        gx, gy = next(label_generator)
        loss = g_fn(gx, gy)
        print 'iter label', i, loss

    for i in range(init_iter_graph):
        gx, gy = next(graph_generator)
        loss = g_fn(gx, gy)
        print 'iter graph', i, loss

In [8]:
init_iter_label = 2000
init_iter_graph = 70
inst_generator = gen_train_inst()
graph_generator = gen_graph()
# Generates pairs with the same label (1) or different labels (-1)
label_generator = gen_label_graph()

In [9]:
gx, gy = next(label_generator)

In [ ]:
feed_dict={X: gx[:, 0], Y: gx[:, 1]}
# feed_dict={X: minibatch_X, Y: minibatch_Y}

In [119]:
with tf.Session() as session:
    tf.global_variables_initializer().run()
    
    feed_dict={g_sym: gx[:, 0], gy_sym: gx[:, 1].reshape(200,1)}
    _, l = session.run([g_optimizer, g_loss], feed_dict=feed_dict)

In [120]:
l

6.5630565

In [117]:
(gx[:, 0].reshape(200, 1)).shape

(200, 1)

In [124]:
tmp = [1,2,3,4,5]
random.choice(tmp)

4